<a href="https://colab.research.google.com/github/shivansh1325/ML-Deep-Learning/blob/main/00Temserflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [ ]:
#create first tensor
tf.constant(8)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
vector=tf.constant([2,3])
vector
vector.ndim

1

In [ ]:
mat=tf.constant([[5,6],
                 [56,7]])
mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  6],
       [56,  7]], dtype=int32)>

In [ ]:
tensor=tf.constant([[[3,4,5],
                    [6,7,8]],
                    [[4,6,7],
                    [7,8,0]],
                    [[4,6,7],
                    [7,8,0]],
                    [[4,6,7],
                    [7,8,0]]])
tensor


<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[3, 4, 5],
        [6, 7, 8]],

       [[4, 6, 7],
        [7, 8, 0]],

       [[4, 6, 7],
        [7, 8, 0]],

       [[4, 6, 7],
        [7, 8, 0]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
changable_scaler=tf.Variable(8)
changable_Vector=tf.Variable([8,9])
changable_matrix=tf.Variable([[8,9],
                              [8,3]])
changable_tensor=tf.Variable([[[3,4,5],
                    [6,7,8]],
                    [[4,6,7],
                    [7,8,0]],
                    [[4,6,7],
                    [7,8,0]],
                    [[4,6,7],
                    [7,8,0]]])


In [ ]:
changable_scaler,
changable_Vector,
changable_matrix,
changable_tensor

<tf.Variable 'Variable:0' shape=(4, 2, 3) dtype=int32, numpy=
array([[[3, 4, 5],
        [6, 7, 8]],

       [[4, 6, 7],
        [7, 8, 0]],

       [[4, 6, 7],
        [7, 8, 0]],

       [[4, 6, 7],
        [7, 8, 0]]], dtype=int32)>

In [ ]:
changable_scaler.assign_add(2)
changable_scaler

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [ ]:
changable_Vector[0].assign(8)
changable_Vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 9], dtype=int32)>

In [ ]:
changable_Vector.assign_add([10,0])
changable_Vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([18,  9], dtype=int32)>

### Creating random tensor

In [ ]:
random_1=tf.random.Generator.from_seed(50)
random_1=random_1.normal(shape=(2,3))
random_2=tf.random.Generator.from_seed(50)
random_2=random_2.normal(shape=(2,3))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.45331386,  1.1487608 , -1.2659091 ],
        [-0.47450137,  2.006022  ,  0.28288034]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.45331386,  1.1487608 , -1.2659091 ],
        [-0.47450137,  2.006022  ,  0.28288034]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True]])>)

In [ ]:
unsuffeled_tensor=tf.random.Generator.from_seed(42)
unsuffeled_tensor=unsuffeled_tensor.normal(shape=(3,2))
unsuffeled_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(4)
tf.random.shuffle(unsuffeled_tensor )

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.ones([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
import numpy as np

In [ ]:
array_A=np.arange(0,50,dtype=int)
array_A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
tf.constant(array_A,shape=(25,2))

<tf.Tensor: shape=(25, 2), dtype=int64, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])>

In [ ]:
rank_4_tensor=tf.ones(shape=(3,5,4,6), dtype=tf.int32)

In [ ]:
rank_4_tensor,tf.size(rank_4_tensor)

(<tf.Tensor: shape=(3, 5, 4, 6), dtype=int32, numpy=
 array([[[[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]]],
 
 
        [[[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 

In [ ]:
rank_4_tensor.ndim,rank_4_tensor[2]

(4,
 <tf.Tensor: shape=(5, 4, 6), dtype=int32, numpy=
 array([[[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],
 
        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],
 
        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],
 
        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],
 
        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]]], dtype=int32)>)

In [ ]:
rank_4_tensor.shape

TensorShape([3, 5, 4, 6])

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3, 5, 4, 6):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 4
Shape of tensor: (3, 5, 4, 6)
Elements along axis 0 of tensor: 3
Elements along last axis of tensor: 6
Total number of elements (3, 5, 4, 6): 360


In [ ]:
rank_4_tensor[:2,:2,:3,:2]

<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]]], dtype=int32)>

In [ ]:
rank_4_tensor.shape

TensorShape([3, 5, 4, 6])

In [ ]:
rank_4_tensor[1:2,:,:,:]

<tf.Tensor: shape=(1, 5, 4, 6), dtype=int32, numpy=
array([[[[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]]]], dtype=int32)>

In [ ]:
scam=tf.ones(shape=(6000,3), dtype=tf.int32)
scam[5:]

<tf.Tensor: shape=(5995, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       ...,
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [ ]:
r2=tf.constant([[1,2],
               [3,4],
                [4,7]])
r2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [4, 7]], dtype=int32)>

In [ ]:
r2[:-1]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
img=tf.zeros(shape=(60000, 28, 28), dtype=tf.int32)
img

<tf.Tensor: shape=(60000, 28, 28), dtype=int32, numpy=
array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0,

In [ ]:
tf.expand_dims(r2,axis=2)

<tf.Tensor: shape=(3, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]],

       [[4],
        [7]]], dtype=int32)>

Basic Operation

In [ ]:
tensor=tf.constant(tf.ones(shape=(90000,2,3)))
tensor

<tf.Tensor: shape=(90000, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       ...,

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.multiply(tensor,10.562)

<tf.Tensor: shape=(90000, 2, 3), dtype=float32, numpy=
array([[[10.562, 10.562, 10.562],
        [10.562, 10.562, 10.562]],

       [[10.562, 10.562, 10.562],
        [10.562, 10.562, 10.562]],

       [[10.562, 10.562, 10.562],
        [10.562, 10.562, 10.562]],

       ...,

       [[10.562, 10.562, 10.562],
        [10.562, 10.562, 10.562]],

       [[10.562, 10.562, 10.562],
        [10.562, 10.562, 10.562]],

       [[10.562, 10.562, 10.562],
        [10.562, 10.562, 10.562]]], dtype=float32)>

In [ ]:
tensor2=tf.constant([[2,7],
                     [3,5],
                     [3,8]])
tensor3=tf.constant([[2,3],
                     [4,6]])
tf.matmul(tensor2,tensor3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[32, 48],
       [26, 39],
       [38, 57]], dtype=int32)>

In [ ]:
tensor2@tensor3

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[32, 48],
       [26, 39],
       [38, 57]], dtype=int32)>

In [ ]:
x=tf.constant([[1,2],
               [3,4],
               [5,6]])
y=tf.constant([[7,8],
               [9,10],
               [3,7]])
x,y
tf.matmul(x,tf.reshape(y,shape=(2,3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[27, 14, 23],
       [61, 36, 55],
       [95, 58, 87]], dtype=int32)>

In [ ]:
tensor=tf.constant([[2,4],
                   [5,7],
                    [7,9]])
tensor1=tf.constant([[3,4],
                   [5,0],
                    [0,9]])
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 4],
       [5, 7],
       [7, 9]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(tensor),tensor1,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 71],
       [47, 97]], dtype=int32)>

In [ ]:
tf.matmul(tensor,tf.reshape(tensor1,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  6,   8,  46],
       [ 15,  20,  88],
       [ 21,  28, 116]], dtype=int32)>

In [ ]:
tf.matmul(tensor,tf.transpose(tensor1))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[22, 10, 36],
       [43, 25, 63],
       [57, 35, 81]], dtype=int32)>

In [ ]:
tensor=tf.constant(tf.ones(shape=(1,256,256,3)))
tensor

<tf.Tensor: shape=(1, 256, 256, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        ...,

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]], dty

In [ ]:
t=tf.constant(tf.ones(shape=(2,3)))
t

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
tf.reshape(t,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

## **Changeing DAta Type**

In [ ]:
tensor=tf.constant([1.3,3.4,5.7],dtype=tf.complex64)
tensor,tensor.dtype

(<tf.Tensor: shape=(3,), dtype=complex64, numpy=array([1.3+0.j, 3.4+0.j, 5.7+0.j], dtype=complex64)>,
 tf.complex64)

In [ ]:
tensor=tf.cast(tensor,tf.int32)
tensor,tensor.dtype

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 3, 5], dtype=int32)>,
 tf.int32)

In [ ]:
t=tf.constant(np.random.randint(low=-100,high=100,size=(100)))
print(t)
print(tf.reduce_max(t))
print(tf.reduce_min(t))
print(tf.reduce_mean(t))
print(tf.reduce_sum(t))
print(tf.abs(t))

tf.Tensor(
[  11   35   58   84   -1    1  -91  -20   80  -47  -10  -55   70  -97
  -69   -3   38  -85  -83   48   77   95   74   64   35   57  -18  -13
   93   93   40  -30   26    3  -55  -30    0  -66  -95  -53  -22  -45
  -51  -49   13  -36  -32   -3   55   64   65  -51  -35  -28   95   34
  -72  -36  -42   87  -42  -74   43  -20   64   90  -90    2  -89  -32
   55   98  -22   -7  -93 -100  -55   28   -5   66   68  -15   -4  -28
   66  -99   94   65  -46  -13    5  -91  -13  -75  -28  -74   26   37
   32   73], shape=(100,), dtype=int64)
tf.Tensor(98, shape=(), dtype=int64)
tf.Tensor(-100, shape=(), dtype=int64)
tf.Tensor(-1, shape=(), dtype=int64)
tf.Tensor(-131, shape=(), dtype=int64)
tf.Tensor(
[ 11  35  58  84   1   1  91  20  80  47  10  55  70  97  69   3  38  85
  83  48  77  95  74  64  35  57  18  13  93  93  40  30  26   3  55  30
   0  66  95  53  22  45  51  49  13  36  32   3  55  64  65  51  35  28
  95  34  72  36  42  87  42  74  43  20  64  90  90   2  89  32  55  

In [ ]:
R=tf.random.Generator.from_seed(42)
R=R.normal(shape=(3,2))
R=tf.constant(np.random.randint(low=0,high=100,size=(30)))
R

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([60,  6, 86, 36, 95, 81, 94, 26, 64, 22, 67, 34, 80, 13, 99, 99, 58,
       81, 88, 27,  7, 42, 78, 68,  4, 39, 77, 96, 59, 41])>

In [ ]:
tf.argmax(R)
tf.argmin(R)

<tf.Tensor: shape=(), dtype=int64, numpy=24>

In [ ]:
G=tf.constant(np.random.randint(0,100,50),shape=(1,1,1,1,50))
G.shape,G.ndim

(TensorShape([1, 1, 1, 1, 50]), 5)

In [ ]:
print(tf.config.list_physical_devices('GPU'))

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
