<a href="https://colab.research.google.com/github/shivansh1325/ML-Deep-Learning/blob/main/00Temserflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
#create first tensor
tf.constant(8)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
vector=tf.constant([2,3])
vector
vector.ndim

1

In [ ]:
mat=tf.constant([[5,6],
                 [56,7]])
mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  6],
       [56,  7]], dtype=int32)>

In [ ]:
tensor=tf.constant([[[3,4,5],
                    [6,7,8]],
                    [[4,6,7],
                    [7,8,0]],
                    [[4,6,7],
                    [7,8,0]],
                    [[4,6,7],
                    [7,8,0]]])
tensor


<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[3, 4, 5],
        [6, 7, 8]],

       [[4, 6, 7],
        [7, 8, 0]],

       [[4, 6, 7],
        [7, 8, 0]],

       [[4, 6, 7],
        [7, 8, 0]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
changable_scaler=tf.Variable(8)
changable_Vector=tf.Variable([8,9])
changable_matrix=tf.Variable([[8,9],
                              [8,3]])
changable_tensor=tf.Variable([[[3,4,5],
                    [6,7,8]],
                    [[4,6,7],
                    [7,8,0]],
                    [[4,6,7],
                    [7,8,0]],
                    [[4,6,7],
                    [7,8,0]]])


In [ ]:
changable_scaler,
changable_Vector,
changable_matrix,
changable_tensor

<tf.Variable 'Variable:0' shape=(4, 2, 3) dtype=int32, numpy=
array([[[3, 4, 5],
        [6, 7, 8]],

       [[4, 6, 7],
        [7, 8, 0]],

       [[4, 6, 7],
        [7, 8, 0]],

       [[4, 6, 7],
        [7, 8, 0]]], dtype=int32)>

In [ ]:
changable_scaler.assign_add(2)
changable_scaler

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>

In [ ]:
changable_Vector[0].assign(8)
changable_Vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([8, 9], dtype=int32)>

In [ ]:
changable_Vector.assign_add([10,0])
changable_Vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([18,  9], dtype=int32)>

### Creating random tensor

In [ ]:
random_1=tf.random.Generator.from_seed(50)
random_1=random_1.normal(shape=(2,3))
random_2=tf.random.Generator.from_seed(50)
random_2=random_2.normal(shape=(2,3))
random_1,random_2,random_1==random_2

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.45331386,  1.1487608 , -1.2659091 ],
        [-0.47450137,  2.006022  ,  0.28288034]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 0.45331386,  1.1487608 , -1.2659091 ],
        [-0.47450137,  2.006022  ,  0.28288034]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=bool, numpy=
 array([[ True,  True,  True],
        [ True,  True,  True]])>)

In [ ]:
unsuffeled_tensor=tf.random.Generator.from_seed(42)
unsuffeled_tensor=unsuffeled_tensor.normal(shape=(3,2))
unsuffeled_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(4)
tf.random.shuffle(unsuffeled_tensor )

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.ones([3,2])

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [ ]:
import numpy as np

In [ ]:
array_A=np.arange(0,50,dtype=int)
array_A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
tf.constant(array_A,shape=(25,2))

<tf.Tensor: shape=(25, 2), dtype=int64, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])>

In [ ]:
rank_4_tensor=tf.ones(shape=(3,5,4,6), dtype=tf.int32)

In [ ]:
rank_4_tensor,tf.size(rank_4_tensor)

(<tf.Tensor: shape=(3, 5, 4, 6), dtype=int32, numpy=
 array([[[[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]]],
 
 
        [[[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1]],
 
         [[1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 1, 1],
          [1, 1, 1, 1, 

In [ ]:
rank_4_tensor.ndim,rank_4_tensor[2]

(4,
 <tf.Tensor: shape=(5, 4, 6), dtype=int32, numpy=
 array([[[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],
 
        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],
 
        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],
 
        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]],
 
        [[1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1],
         [1, 1, 1, 1, 1, 1]]], dtype=int32)>)

In [ ]:
rank_4_tensor.shape

TensorShape([3, 5, 4, 6])

In [ ]:
rank_4_tensor.ndim

4

In [ ]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3, 5, 4, 6):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 4
Shape of tensor: (3, 5, 4, 6)
Elements along axis 0 of tensor: 3
Elements along last axis of tensor: 6
Total number of elements (3, 5, 4, 6): 360


In [ ]:
rank_4_tensor[:2,:2,:3,:2]

<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
array([[[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]],


       [[[1, 1],
         [1, 1],
         [1, 1]],

        [[1, 1],
         [1, 1],
         [1, 1]]]], dtype=int32)>

In [ ]:
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 6), dtype=int32, numpy=array([[[[1, 1, 1, 1, 1, 1]]]], dtype=int32)>