In [3]:
import tensorflow as tf
import numpy as np

In [4]:
tf.__version__

'2.17.0'

In [5]:
tf.constant(np.random.randint(0,50,size=(3,2)))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[42,  2],
       [11, 12],
       [28, 34]])>

In [10]:
tf.constant(np.random.randint(0,100,10))

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([49, 46, 81, 42, 74, 72, 82, 13, 34, 71])>

In [18]:
f=tf.constant(tf.ones(shape=(2,3)))
f

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>