<a href="https://colab.research.google.com/github/shivansh1325/ML-Deep-Learning/blob/main/01_Neural_Network_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
tf.constant(np.random.randint(0,50,size=(3,3)))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[12,  8, 33],
       [15, 35, 10],
       [ 8, 36,  4]])>

In [4]:
tf.random.uniform(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.31741285, 0.6107222 , 0.71810997],
       [0.4521147 , 0.31512392, 0.53984797],
       [0.08741915, 0.17149651, 0.68231297]], dtype=float32)>